server:
  port: 8088

# registering with eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# routes configuration
spring:
  cloud:
    gateway:
      routes:
        - id: BANK-SERVICE
          uri:
            lb://BANK-SERVICE
          predicates:
            - Path=/bank/**

        - id: BRANCH-SERVICE
          uri:
            lb://BRANCH-SERVICE
          predicates:
            - Path=/branch/**

        - id: CUSTOMER-SERVICE
          uri:
            lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**

  application:
    name: API-GATEWAY