spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Code-Chetan/Configuration_For_Banking-Microservices
          clone-on-start: true
server:
  port: 8089


